import { Box, Container, SimpleGrid } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/header";
import { VideoPreviewCardLink } from "../components/video-preview-card-link";
import { useApiFetchYoutubeVideos } from "../services/apis/use-api-fetch-youtube-videos";

const Home: NextPage = () => {
  const { data, isLoading } = useApiFetchYoutubeVideos({});

  return (
    <div>
      <Head>
        <title>YouTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.xl" marginTop={4}>
        <Box mb={4}>
          <Header />
        </Box>
        <hr />

        {isLoading && <h1>Loading</h1>}

        <SimpleGrid columns={4} spacing={4} marginTop={4}>
          {data?.items.map(({ snippet, id }) => (
            <VideoPreviewCardLink id={id} snippet={snippet} key={id} />
          ))}
        </SimpleGrid>
      </Container>
    </div>
  );
};

export default Home;
