import {
  Button,
  Container,
  Flex,
  FormControl,
  Input,
  InputGroup,
  InputRightAddon,
  Link,
  SimpleGrid,
  Text
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { VideoPreviewCardLink } from "../components/video-preview-card-link";
import { useApiFetchYoutubeVideos } from "../services/apis/use-api-fetch-youtube-videos";

const Home: NextPage = () => {
  const { data, isLoading } = useApiFetchYoutubeVideos({});

  return (
    <div>
      <Head>
        <title>YouTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.xl" marginTop={4}>
        <Flex
          mb={4}
          as="header"
          justifyContent="space-between"
          alignItems="center"
        >
          <Image
            src="/assets/youtube-svgrepo-com.svg"
            width={50}
            height={50}
            alt="youtube logo"
          />

          <Flex>
            <FormControl w={600}>
              <InputGroup>
                <Input placeholder="search your video" />
                <InputRightAddon>
                  <Button>Search</Button>
                </InputRightAddon>
              </InputGroup>
            </FormControl>
          </Flex>

          <Flex gap={2}>
            <Link color="red.500">Create account</Link>
            <Text>or</Text>
            <Link color="red.500">Sign in</Link>
          </Flex>
        </Flex>
        <hr />

        {isLoading && <h1>Loading</h1>}

        <SimpleGrid columns={4} spacing={4} marginTop={4}>
          {data?.items.map(({ snippet, id }) => (
            <VideoPreviewCardLink id={id} snippet={snippet} key={id} />
          ))}
        </SimpleGrid>
      </Container>
    </div>
  );
};

export default Home;
