import { Container, Grid, GridItem } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Header } from "../components/header";
import { VideoGridList } from "../components/video-grid-list";
import { VideoPlayer } from "../components/video-player";
import { useApiFetchYoutubeVideos } from "../services/apis/use-api-fetch-youtube-videos";

const Watch: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;
  const { data, isFetching } = useApiFetchYoutubeVideos({});
  // const { vid } = useApiFetchYoutubeVideoById({ id });

  return (
    <div>
      <Head>
        <title>YouTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.xl" marginTop={4}>
        <Header />
        <hr />

        <Grid
          mt={2}
          h="500px"
          templateRows="repeat(1, 1fr)"
          templateColumns="repeat(6, 1fr)"
          gap={4}
        >
          <GridItem rowSpan={2} colSpan={6}>
            <VideoPlayer videoId={id as string} />
          </GridItem>
        </Grid>

        {isFetching || !data?.items.length ? (
          <h1>Loading</h1>
        ) : (
          <VideoGridList data={data?.items} />
        )}
      </Container>
    </div>
  );
};

export default Watch;
