import { Container } from "@chakra-ui/react";
import Head from "next/head";
import { Header } from "./header";

type AppLayoutProps = {
  children: React.ReactNode;
};

export const AppLayout = ({ children }: AppLayoutProps) => {
  return (
    <div>
      <Head>
        <title>YouTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.xl" marginTop={4}>
        <Header />
        <hr />

        {children}
      </Container>
    </div>
  );
};
